from dotenv import load_dotenv
import os

load_dotenv()

GTFS_REALTIME_ALERTS_URL = os.getenv("GTFS_REALTIME_ALERTS_URL")
GTFS_REALTIME_TRIP_UPDATES_URL = os.getenv("GTFS_REALTIME_TRIP_UPDATES_URL")
GTFS_REALTIME_VEHICLE_POSITION_URL = os.getenv("GTFS_REALTIME_VEHICLE_POSITION_URL")
